{{- $skipSecrets := .Values.skipSecrets -}}
{{ if not $skipSecrets }}
{{- $shEndpoint := .Files.Get (printf "secrets/SH_DB_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $orgSvcUrl := .Files.Get (printf "secrets/ORG_SVC_URL.%s.secret" .Values.deployEnv) -}}
{{- $userSvcUrl := .Files.Get (printf "secrets/USER_SVC_URL.%s.secret" .Values.deployEnv) -}}
{{- $awsRegion := .Files.Get (printf "secrets/AWS_REGION.%s.secret" .Values.deployEnv) -}}
{{- $awsKey := .Files.Get (printf "secrets/AWS_KEY.%s.secret" .Values.deployEnv) -}}
{{- $awsSecret := .Files.Get (printf "secrets/AWS_SECRET.%s.secret" .Values.deployEnv) -}}
{{- $awsTopic := .Files.Get (printf "secrets/AWS_TOPIC.%s.secret" .Values.deployEnv) -}}
{{- $lfAuth := .Files.Get (printf "secrets/LF_AUTH.%s.secret" .Values.deployEnv) -}}
---
apiVersion: v1
data:
  SH_DB_ENDPOINT.secret: {{ $shEndpoint | b64enc }}
  ORG_SVC_URL.secret: {{ $orgSvcUrl | b64enc }}
  USER_SVC_URL.secret: {{ $userSvcUrl | b64enc }}
  AWS_REGION.secret: {{ $awsRegion | b64enc }}
  AWS_KEY.secret: {{ $awsKey | b64enc }}
  AWS_SECRET.secret: {{ $awsSecret | b64enc }}
  AWS_TOPIC.secret: {{ $awsTopic | b64enc }}
  LF_AUTH.secret: {{ $lfAuth | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.syncSecret }}
  labels:
    type: 'secret'
    app.kubernetes.io/name: {{ include "sfdc-sh-sync.name" . }}
    helm.sh/chart: {{ include "sfdc-sh-sync.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ end }}
