{{- $skipSecrets := .Values.skipSecrets -}}
{{ if not $skipSecrets }}
{{- $shEndpoint := .Files.Get (printf "secrets/SH_DB_ENDPOINT.%s.secret" .Values.deployEnv) -}}
{{- $notifSvcUrl := .Files.Get (printf "secrets/NOTIF_SVC_URL.%s.secret" .Values.deployEnv) -}}
{{- $orgSvcUrl := .Files.Get (printf "secrets/ORG_SVC_URL.%s.secret" .Values.deployEnv) -}}
{{- $userSvcUrl := .Files.Get (printf "secrets/USER_SVC_URL.%s.secret" .Values.deployEnv) -}}
{{- $affApiUrl := .Files.Get (printf "secrets/AFF_API_URL.%s.secret" .Values.deployEnv) -}}
{{- $awsRegion := .Files.Get (printf "secrets/AWS_REGION.%s.secret" .Values.deployEnv) -}}
{{- $awsKey := .Files.Get (printf "secrets/AWS_KEY.%s.secret" .Values.deployEnv) -}}
{{- $awsSecret := .Files.Get (printf "secrets/AWS_SECRET.%s.secret" .Values.deployEnv) -}}
{{- $awsTopic := .Files.Get (printf "secrets/AWS_TOPIC.%s.secret" .Values.deployEnv) -}}
{{- $auth0Url := .Files.Get (printf "secrets/AUTH0_URL.%s.secret" .Values.deployEnv) -}}
{{- $auth0Audience := .Files.Get (printf "secrets/AUTH0_AUDIENCE.%s.secret" .Values.deployEnv) -}}
{{- $auth0ClientID := .Files.Get (printf "secrets/AUTH0_CLIENT_ID.%s.secret" .Values.deployEnv) -}}
{{- $auth0ClientSecret := .Files.Get (printf "secrets/AUTH0_CLIENT_SECRET.%s.secret" .Values.deployEnv) -}}
{{- $gitdmSyncUrl := .Files.Get (printf "secrets/GITDM_SYNC_URL.%s.secret" .Values.deployEnv) -}}
---
apiVersion: v1
data:
  SH_DB_ENDPOINT.secret: {{ $shEndpoint | b64enc }}
  NOTIF_SVC_URL.secret: {{ $notifSvcUrl | b64enc }}
  ORG_SVC_URL.secret: {{ $orgSvcUrl | b64enc }}
  USER_SVC_URL.secret: {{ $userSvcUrl | b64enc }}
  AFF_API_URL.secret: {{ $affApiUrl | b64enc }}
  AWS_REGION.secret: {{ $awsRegion | b64enc }}
  AWS_KEY.secret: {{ $awsKey | b64enc }}
  AWS_SECRET.secret: {{ $awsSecret | b64enc }}
  AWS_TOPIC.secret: {{ $awsTopic | b64enc }}
  AUTH0_URL.secret: {{ $auth0Url | b64enc }}
  AUTH0_AUDIENCE.secret: {{ $auth0Audience | b64enc }}
  AUTH0_CLIENT_ID.secret: {{ $auth0ClientID | b64enc }}
  AUTH0_CLIENT_SECRET.secret: {{ $auth0ClientSecret | b64enc }}
  GITDM_SYNC_URL.secret: {{ $gitdmSyncUrl | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.syncSecret }}
  labels:
    type: 'secret'
    app.kubernetes.io/name: {{ include "ssaw.name" . }}
    helm.sh/chart: {{ include "ssaw.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ end }}
