# skipSecrets (will not attempt to create secrets, if you want to create new secrets delete current secrets first and do not set this flag)
# skipNamespace (will skip ssaw namespace creation)
# skiSync (will skip deploying main sync pod)
# skipSecrets: 1
# skipNamespace: 1
# skiSync: 1
# dryRun: '1'
# Standard values:
deployEnv: 'set-me'
dryRun: ''
concurrencyPolicy: Forbid
fullnameOverride: ssaw
imagePullPolicy: Always
syncCommand: '/usr/bin/ssaw'
syncImage: 'lukaszgryglicki/ssaw'
syncServiceName: ssaw-service
syncPodName: ssaw
syncRestartPolicy: Always
syncSecret: ssaw-secret
name: ssaw
namespace: ssaw
nameOverride: ssaw
secretType: Opaque
