# skipSecrets (will not attempt to create secrets, if you want to create new secrets delete current secrets first and do not set this flag)
# skipNamespace (will skip sfdc-sh-sync namespace creation)
# skiSync (will skip deploying main sync pod)
# skipSecrets: 1
# skipNamespace: 1
# skiSync: 1
# dryRun: '1'
# Standard values:
deployEnv: 'set-me'
dryRun: ''
concurrencyPolicy: Forbid
fullnameOverride: sfdc-sh-sync
imagePullPolicy: Always
syncCommand: '/usr/bin/sfdc-sh-sync'
syncImage: 'lukaszgryglicki/lf-sfdc-sh-sync'
syncServiceName: sfdc-sh-sync-service
syncPodName: sfdc-sh-sync
syncRestartPolicy: Always
syncSecret: sfdc-sh-sync-secret
name: sfdc-sh-sync
namespace: sfdc-sh-sync
nameOverride: sfdc-sh-sync
secretType: Opaque
